name: at_robot

on: 
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  run_test_cases:
    if: |
      contains(github.event.comment.body, '@cocos-robot run test cases')
    runs-on: ubuntu-latest
    #runs-on: run-test-win01
    steps:
      - uses: actions/checkout@v2
        #with:
        #  path: engine    
      - name: run test cases
        run: |
          echo "call run test cases"
